In [2]:
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf
from tensorflow.nn import convolution


Y = np.array([[0,0,0], [0,-1,0], [0,0,0]])
Z = np.array([[0,0,0], [0, 1,0], [0,0,0]])

Z1 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), Z.reshape(3,3,1)], axis=2)

Y = np.array([[0,0,0], [0,1,0], [0,-1,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

F1 = np.concatenate([np.zeros((3,3,3, 1)), Z1.reshape(3,3,3,1), Z2.reshape(3,3,3,1)], axis=3)

Y = np.array([[0,0,0], [0, 1,0], [0,0,0]])
Z = np.array([[0,0,0], [0,-1,0], [0,0,0]])

Z1 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), Z.reshape(3,3,1)], axis=2)

Y = np.array([[0,0,0], [0,-1,0], [0,0,0]])
Z = np.array([[0,0,0], [0, 1,0], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), Z.reshape(3,3,1)], axis=2)

F2 = np.concatenate([Z1.reshape(3,3,3,1), np.zeros((3,3,3, 1)),Z2.reshape(3,3,3,1)], axis=3)

Y = np.array([[0,0,0], [0,1,0], [0,-1,0]])

Z1 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1),np.zeros((3,3,1))], axis=2)

Y = np.array([[0,0,0], [0,-1,1], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

F3 = np.concatenate([Z1.reshape(3,3,3,1), Z2.reshape(3,3,3,1), np.zeros((3,3,3, 1))], axis=3)

faraday_filter = np.concatenate([F1.reshape(3,3,3,3,1), F2.reshape(3,3,3,3,1), F3.reshape(3,3,3,3,1)], axis=4)

In [6]:
X = np.array([[0,0,0], [0,-1,0], [0,0,0]])
Y = np.array([[0,0,0], [0, 1,0], [0,0,0]])

Z1 = np.concatenate([X.reshape(3,3,1), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

Y = np.array([[0,-1,0], [0,1,0], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

F1 = np.concatenate([np.zeros((3,3,3, 1)), Z1.reshape(3,3,3,1), Z2.reshape(3,3,3,1)], axis=3)

X = np.array([[0,0,0], [0, 1,0], [0,0,0]])
Y = np.array([[0,0,0], [0,-1,0], [0,0,0]])

Z1 = np.concatenate([X.reshape(3,3,1), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

Y = np.array([[0,0,0], [1,-1,0], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

F2 = np.concatenate([Z1.reshape(3,3,3,1), np.zeros((3,3,3, 1)),Z2.reshape(3,3,3,1)], axis=3)

Y = np.array([[0,-1,0], [0,1,0], [0,0,0]])

Z1 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

Y = np.array([[0,0,0], [1,-1,0], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

F3 = np.concatenate([Z1.reshape(3,3,3,1), Z2.reshape(3,3,3,1), np.zeros((3,3,3, 1))], axis=3)

ampere_filter = np.concatenate([F1.reshape(3,3,3,3,1), F2.reshape(3,3,3,3,1), F3.reshape(3,3,3,3,1)], axis=4)

In [10]:
Y = np.array([[0,0,0], [1, -1,0], [0,0,0]])

Z1 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

Y = np.array([[0,1,0], [0,-1,0], [0,0,0]])

Z2 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

X = np.array([[0,0,0], [0,1,0], [0,0,0]])
Y = np.array([[0,0,0], [0,-1,0], [0,0,0]])

Z3 = np.concatenate([np.zeros((3,3,1)), Y.reshape(3,3,1), np.zeros((3,3,1))], axis=2)

continuity_filter = np.concatenate([Z1.reshape(3,3,3,1), Z2.reshape(3,3,3,1), Z3.reshape(3,3,3,1)], axis=3).reshape(3,3,3,3,1)

In [11]:
d = np.zeros((5,5,5,3))
d[2,2,2,1] = 1
E = tf.Variable(d.reshape((1, 5, 5, 5, 3)), name='e_field', dtype=tf.float64)

r = convolution(convolution(E, filters=ampere_filter, padding='SAME'), filters=continuity_filter, padding='SAME').numpy()
r = np.squeeze(r)

In [82]:
d = np.random.uniform(0,1,(5,5,5,3))
#d = np.zeros((5,5,5,3))
#d[3-1,3,3,2]=1
E = tf.Variable(d.reshape((1, 5, 5, 5, 3)), name='e_field', dtype=tf.float64)

r = convolution(E, filters=ampere_filter, padding='SAME').numpy()
r = np.squeeze(r)

In [83]:
r

array([[[[ 0.97555492, -0.59301075, -0.38254417],
         [ 0.46793403, -1.26202625,  0.41154805],
         [ 1.32888029, -0.36636641, -0.55096583],
         [ 0.64145182, -0.87613217, -0.31628547],
         [ 0.33335624, -0.63270499, -0.01693672]],

        [[ 0.80656251, -1.08193637,  1.25092878],
         [ 0.09752062,  1.44434965,  0.17699254],
         [ 0.48735203,  0.66378029,  0.35474052],
         [ 0.48495775,  0.15040111,  0.36083349],
         [ 0.39653778, -0.4275711 ,  0.72522304]],

        [[ 0.32642943, -0.13068104,  0.61081413],
         [ 1.34774765, -1.12486626,  0.48545335],
         [ 0.61764692,  0.54200685, -0.18684839],
         [-0.2280073 ,  0.09364178,  0.43247487],
         [ 1.24722529,  0.14309304, -0.56130568]],

        [[ 0.62597006, -0.40865396,  0.10911333],
         [ 0.94489548,  0.4199837 ,  0.0919818 ],
         [-0.17065716, -0.04760014,  0.92788602],
         [ 0.51272259,  0.26615423, -0.0789981 ],
         [ 0.64435159, -0.65749367,  1.18136

In [84]:
r[3,3,3,0]

0.13207396927737947

In [85]:
-E[0,3,3,3-1,1] + E[0,3,3,3,1] + E[0,3,3,3,2] - E[0,3-1,3,3,2]

<tf.Tensor: shape=(), dtype=float64, numpy=0.13207396927737947>

In [86]:
r[3,3,3,0]

0.13207396927737947

In [87]:
ampere_filter[:,:,1,2,0]

array([[ 0., -1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [89]:
np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10),np.linspace(0,1,10)).__len__()

3